#!/bin/bash
#This script is executed every time your instance is spawned.
# shellcheck disable=SC2117
home=/home/j1v37u2k3y
cd "${home}" || exit
git clone https://github.com/welikechips/chips "${home}/chips"
# setup chips directory
sudo ln -s "${home}/chips/menu.py" /usr/local/bin/chips
echo "2" | "${home}/chips/scripts/Installs/bashrc.sh"
cd "${home}" || exit
git clone https://github.com/welikechips/.tmux.git
git clone https://github.com/tmux-plugins/tpm .tmux/plugins/tpm
ln -s -f .tmux/.tmux.conf .
cp .tmux/.tmux.conf.local .
